#import "./fragments.gql"

query GetUsers {
  users {
    ...UserInfo
  }
}

query GetPosts {
  posts {
    ...PostInfo
  }
}

query GetUserPosts($authorId: String!) {
  posts(where: { authorId: { equals: $authorId }}) {
    ...PostInfo
  }
}
