#import "./fragments.gql"

query GetUsers {
  users {
    ...UserInfo
  }
}

query GetUser($id: String!) {
  user (where: {id: $id}) {
    id
    email
    firstName
    lastName
  }
}

query GetMyUser {
  myUser {
    id
    firstName
  }
}

query GetPosts {
  posts {
    ...PostInfo
  }
}

query GetUserPosts($authorId: String!) {
  posts(where: { authorId: { equals: $authorId }}) {
    ...PostInfo
  }
}
